_BASE_: "Base-HierText-Polygon.yaml"
MODEL:
  WEIGHTS: "ckp/pretrain_testr_R_50_polygon.pth"
  RESNETS:
    DEPTH: 50
  TRANSFORMER:
    NUM_FEATURE_LEVELS: 4
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.1
    NHEADS: 8
    NUM_QUERIES: 100
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
    ENCODER_WEIGHTS: "ckp/regex_encoder_256_dim.pth" # Alternative: "ckp/regex_encoder_256_dim.pth"
    ENCODER_DIM: 256 # Make sure to match this with the encoder weights
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (60000,200000)
  MAX_ITER: 600000
  CHECKPOINT_PERIOD: 25000
TEST:
  EVAL_PERIOD: 15000
OUTPUT_DIR: "output/TESTR/HierText/STEP_50_Polygon"
